name = "gleamfonts"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gluid = ">= 1.0.0 and < 2.0.0"
hackney = ">= 1.20.1 and < 2.0.0"
gleescript = ">= 1.4.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"
glesha = ">= 0.1.4 and < 1.0.0"

[dev-dependencies]
startest = ">= 0.5.0 and < 1.0.0"
