name = "gleamfonts"
version = "1.0.1"
description = "Command-line tool to fetch and install fonts from NerdFonts repository"
licences = ["MIT"]

[repository]
type = "github"
user = "massix"
repo = "gleamfonts"

[[links]]
title = "GitHub Repository"
href = "https://github.com/massix/gleamfonts"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gluid = ">= 1.0.0 and < 2.0.0"
hackney = ">= 1.20.1 and < 2.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"
glesha = ">= 0.1.4 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
startest = ">= 0.5.0 and < 1.0.0"
