name: release
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.0"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: sudo apt update && sudo apt install -y libsqlite3-dev
      - run: sqlite3 --version
      - run: make dist
      - uses: softprops/action-gh-release@v2
        with:
          files: gleamfonts-*.tgz
          draft: false
          name: "gleamfonts ${{ github.ref_name }}"
          mke_latest: "true"
