name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.1"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - run: sudo apt update && sudo apt install -y libsqlite3-dev
      - run: sqlite3 --version
      - run: make build
      - run: make test
  dist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.1"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - run: sudo apt update && sudo apt install -y libsqlite3-dev
      - run: sqlite3 --version
      - run: make dist
      - run: ls *.tgz
