name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.0"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: sudo apt update && sudo apt install -y libsqlite3-dev
      - run: sqlite3 --version
      - run: make build
      - run: make test
  dist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.0"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: sudo apt update && sudo apt install -y libsqlite3-dev
      - run: sqlite3 --version
      - run: make dist
      - run: ls *.tgz
